### PR TITLE
Improve server management

### PR DESCRIPTION
**Pull request by Keoghan**
- Be more cautious with using/creating Dusk server. Fail if a server (or process) already exists on the host/port we want to use.
- Add a shutdown_function to handle stopping the server if the test is prematurely closed (e.g. dd() or exit()).
- Swap to using the Symfony Process class for starting and stopping the separate server process.  Allows us to remove ProcessUtils as well.
- Add 'exec' to the process command, which allows a clean shutdown on Ubuntu (found through Travis). (Relevant bug report for Symfony here: symfony/symfony#23568)

### CODE REVIEW

**Comment by Keoghan** [comment]
@crynobone - if you have time, I'd appreciate your thoughts on this. I realise you're probably pretty busy with updating all your other packages with 5.6 compatibility though - so no rush.

**Comment by crynobone** [comment]
Looks good, but I not sure why this is targetting `master`, which is for Laravel 5.7

**Comment by Keoghan** [comment]
Thanks for taking a look. I had worked on 3.5 then rebased to master in order to flow back down. 

Is it better to target 3.4 and then pull back up through 3.5,3.6 and then master? I’m still getting used to managing the multiple live branches :)

**Comment by crynobone** [comment]
Would be good if you can work it out to `3.4`, but we should be at least make it working for `3.5` since Laravel 5.5 is LTS.

**Comment by Keoghan** [comment]
Hmm, that doesn't look right to me - sorry, I'll close this PR, and retarget 3.4 if possible otherwise 3.5.

**Pull request closed without merging**
