### PR TITLE
update server.php make files browsable

### PR DESCRIPTION
**Pull request by moxx**
make it possible to publish various assets and files to the public folder and serve them

### CODE REVIEW

**Comment by Keoghan** [comment]
Thanks for this moxx. Will take a look at adding to the 5.5 branch tomorrow, and resolve the master issues with the php7.1 restrictions.

**Comment by moxx** [comment]
thx 👍🏻

**Comment by Keoghan** [comment]
@moxx I have merged your change as you'll see. The breaks on Travis are due to composer struggling to knit together all the components at the moment - but Laravel 5.6 and all the related components aren't stable yet.

I have also added into the 3.4 and 3.5 branches to support Laravel 5.4 and 5.5.

**Comment by crynobone** [comment]
>  The breaks on Travis are due to composer struggling to knit together all the components at the moment - but Laravel 5.6 and all the related components aren't stable yet.

The dependencies already updated, now we need to make sure the code compatible with `symfony/process` `v4.0+`.

**Pull request merged**
