### PR TITLE
Bump to laravel dusk 5.0

### PR DESCRIPTION
**Pull request by crynobone**
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

### CODE REVIEW

**Comment by crynobone** [comment]
Merged

**Comment by Keoghan** [comment]
thanks @crynobone - lots of stuff on here today!

**Comment by crynobone** [comment]
@Keoghan no problem, just have some available time today to look into this. But I don't have any project using `orchestra/testbench-dusk`. Might want to look if anything doesn't work as expected.

**Comment by crynobone** [comment]
BTW `master` is failing right now, but I suspect is due to <https://github.com/laravel/framework/commit/c37702cbdedd4e06eba2162d7a1be7d74362e0cf> not yet available in 5.9

**Pull request closed without merging**
