### PR TITLE
change process STDERR to pipe

### PR DESCRIPTION
**Pull request by moxx**
post STDERR in pipe for hide all 200 GET outputs from cli. Laravel dusk alrady handle console errors.

### CODE REVIEW

**Comment by Keoghan** [comment]
Hi @moxx, 

Please can you rebase this with the master branch? I've just updated the phpunit requirements there which should allow your changes to pass on Travis.

Thanks

**Comment by moxx** [comment]
done

**Comment by Keoghan** [comment]
Thanks @moxx. 

Are you using a particular version at the moment, that you would like this back-ported to?

**Comment by moxx** [comment]
yes 3.5

**Comment by Keoghan** [comment]
3.5.3 tagged

**Pull request merged**
